### ISSUE TITLE
the dist client code size is huge

### ISSUE THREAD

**Issue by dportabella** [amejiarosario/meanshop#36]
running `grunt build` creates the `dist` folder, with all the client scripts and css concatenated and minified. These are the files:
```
 28Kb app.2478a1c2.js
129Kb app.79e4c1fe.css
641Kb vendor.9531310c.js
  0Kb vendor.d41d8cd9.css
```
the web browser needs to download almost 1Mb before seeing anything. I hated this type of web applications when I was traveling in Asia with a slow internet connection. Is there a solution for this?

Also, in the dist directory:
```
dist/Procfile
dist/client/app
dist/client/assets
dist/client/bower_components
dist/client/favicon.ico
dist/client/index.html
dist/client/robots.txt
dist/package.json
dist/server/...
```
there is `client/bower_components/`  (9.7Mb)
I tried deleting this folder, and the application runs ok.
Is this directory really needed?
or everything needed here is already compiled in the `client/app/vendor.9531310c.js`?
if it can be deleted, why does `grunt build` not clean it?

This is a question, not an issue. Where should I post questions?

**Comment by amejiarosario** [comment]
You are right. Single Page Applications (SPA) build with Angular 1 requires the browser to download all javascript first before loading page. They are [fixing that in Angular 2](https://angularu.com/VideoSession/2015sf/angular-2-server-rendering), where they render the html in the server side and minimize the time the user .

In the meantime while using Angular 1, if you have the cache enabled you will only need to download the files once and then the browser will use the cache instead of downloading it all the time.

And yes, `client/bower_components/` -> `vendor.*.js`. Use `grunt clean` to [clean](https://github.com/amejiarosario/meanshop/blob/master/Gruntfile.js#L155) compiled assets

**Comment by dportabella** [comment]
ok, thanks.
is it ok to pose questions here (github issues), or is it there a better place (eg packtlib)?

**Comment by amejiarosario** [comment]
@dportabella I think this is the best place to post questions/issues and enhancements ideas. I can reply to them quickly and also other people can benefit from the answers
