### ISSUE TITLE
Heroku deploy does not populate database

### ISSUE THREAD

**Issue by cosjef** [amejiarosario/meanshop#39]
I followed the instructions for a Heroku deployment (https://afternoon-savannah-33109.herokuapp.com), but nothing was populated in Mongo. Is there a missing step to populate the collections with documents?

![2016-04-08_00-06-25](https://cloud.githubusercontent.com/assets/423400/14373944/e8408b9e-fd1d-11e5-89d2-9d8d78cacaff.png)

**Comment by amejiarosario** [comment]
Hi @cosjef 

That's working by design. When you deploy the app to heroku is working in production mode. If you check the code https://github.com/amejiarosario/meanshop/blob/master/server/config/environment/index.js#L28 is set to false. Development mode is the only one that seeds the database. Test and production doesn't. 

You can change it to true `seedDB: true` and re-deploy and It will populate it.
