### ISSUE TITLE
not able to find any css documents on any page...

### ISSUE THREAD

**Issue by Deadpool1994** [amejiarosario/meanshop#43]
Error on npm install:
 node-pre-gyp install --fallback-to-build

Using Ubuntu 15.04

homepage works fine but it show no css.

The entire error log - 
npm WARN EPEERINVALID mongodb-core@1.2.31 requires a peer of kerberos@~0.0 but none was installed.
npm WARN EPEERINVALID karma-phantomjs-launcher@0.2.3 requires a peer of phantomjs@>=1.9 but none was installed.
npm ERR! Linux 3.19.0-49-generic
npm ERR! argv "/home/alchemist/.nvm/versions/node/v5.0.0/bin/node" "/home/alchemist/.nvm/versions/node/v5.0.0/bin/npm" "install"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE

npm ERR! v8-debug@0.4.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-debug@0.4.6 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/alchemist/meanshop/npm-debug.log

**Comment by amejiarosario** [comment]
@Deadpool1994  Did you installed the bower packages `bower install`? 
Make sure you follow the steps detailed on https://github.com/amejiarosario/meanshop#installation

**Comment by jc184** [comment]
I've got a similar problem, which is caused In think by the fact that I can't seem to install sass using `gem install sass`. I've got Ruby installed using `rbenv`. When I try to install `sass` via the terminal, this is what I get:
`Building native extensions.  This could take a while...
ERROR:  Error installing sass:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/ffi-1.9.18/ext/ffi_c
/usr/bin/ruby2.3 -r ./siteconf20171020-14278-b9patm.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1
`
Am I doing something wrong?

**Comment by amejiarosario** [comment]
@jc184 try
`gem uninstall compass && gem uninstall sass && gem install compass`

Compass will install a compatible version of sass automatically.

**Comment by jc184** [comment]
Thanks for the tip, but I got it working by resolving PATH issues. My app works perfectly now.I wanted to say I really enjoyed your book!‎ Regards James Chalmers                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Adrian MejiaSent: Friday, 20 October 2017 20:59To: amejiarosario/meanshopReply To: amejiarosario/meanshopCc: james chalmers; MentionSubject: Re: [amejiarosario/meanshop] not able to find any css documents on any page... (#43)@jc184 try
gem uninstall compass && gem uninstall sass && gem install compass
Compass will install a compatible version of sass automatically.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/amejiarosario/meanshop","title":"amejiarosario/meanshop","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/amejiarosario/meanshop"}},"updates":{"snippets":[{"icon":"PERSON","message":"@amejiarosario in #43: @jc184 try\r\n`gem uninstall compass \u0026\u0026 gem uninstall sass \u0026\u0026 gem install compass`\r\n\r\nCompass will install a compatible version of sass automatically."}],"action":{"name":"View Issue","url":"https://github.com/amejiarosario/meanshop/issues/43#issuecomment-338307830"}}}

**Comment by amejiarosario** [comment]
Glad to hear!
